items:
  mjolnir:
    display: Mjølnir
    item:
      id: iron_shovel
    crafting:
      - [iron_block, iron_ingot, iron_block]
      - [air, wooden_stick, air]
      - [air, wooden_stick, air]
    binds:
      - lightning
spells:
  lightning:
    display: LIGHTNING STRIKE
    scripts:
      - script: summon_at_target
        options:
          entities:
            - id: lightning_strike
          damage:
            amount: 10
            areaOfEffect: 2
