name: SpellCastr
version: 0.0.1
description: Provides an API for server ops to add spells which players can use in-game.
author: theonlygusti <https://github.com/theonlygusti/>
main: io.github.theonlygusti.spellcastr.Plugin
